/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipo3p;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ConsultaAsignacionCursosAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaAsignacionCursosAlumnos
     */
    public ConsultaAsignacionCursosAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        combo = new javax.swing.JTable();
        cboBuscar = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setVisible(true);

        combo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        combo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carnet", "Nombre", "Curso", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(combo);

        cboBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(cboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscar)
                    .addComponent(cboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(52, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       
        DefaultTableModel modelo = new DefaultTableModel();
       
       try{
           
            Connection cnR = DriverManager.getConnection("jdbc:mysql://localhost/siu", "root", "compromiso");

            PreparedStatement pstR = cnR.prepareStatement("select * from asignacioncursosalumnos where carnet_alumno = ?");
            pstR.setString(1, cboBuscar.getSelectedItem().toString());
            ResultSet rsR = pstR.executeQuery();
                     
            if(rsR.next()){
                
                
           
           
                try{

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/siu", "root", "compromiso");
            PreparedStatement pst = cn.prepareStatement("select * from asignacioncursosalumnos where carnet_alumno = ?");
            pst.setString(1, (String) this.cboBuscar.getSelectedItem());
            modelo.addColumn("Carnet");
            modelo.addColumn("Nombre");
            modelo.addColumn("Curso");
            modelo.addColumn("Nota");
            ResultSet rs = pst.executeQuery();   
            
               while(rs.next()){
                             
                String codigo_curso = "", carnet_alumno="";
                float nota = 0;     
                            
                        codigo_curso = String.valueOf(rs.getString("codigo_curso"));
                        carnet_alumno = String.valueOf(rs.getString("carnet_alumno"));   
                        nota = Float.parseFloat(rs.getString("nota_asignacioncursoalumnos"));
                
                        
                        
              PreparedStatement pst1 = cn.prepareStatement("select * from alumnos where carnet_alumno = " + carnet_alumno);
              ResultSet rs1 = pst1.executeQuery();
                
                
                while(rs1.next()){          
                        
                String nombre_alumno = "";                
                nombre_alumno = String.valueOf(rs1.getString("nombre_alumno"));            
                
                PreparedStatement pst2 = cn.prepareStatement("select * from cursos where codigo_curso = " + codigo_curso);
                ResultSet rs2 = pst2.executeQuery();
                
             
                String nombre_curso = "";
                
            while(rs2.next()){
                
                nombre_curso = String.valueOf(rs2.getString("nombre_curso"));
                    
                    Object filas[] = {carnet_alumno,nombre_alumno,nombre_curso,nota};
                    modelo.addRow(filas);
                    
                    combo.setModel(modelo);
                
              }                
                        
            }    
                
         }
            
          
            
        
            
        }catch(Exception e){
              JOptionPane.showMessageDialog(null, "Error");
        }
                
                
                
           
           
           
           
           
       }else{
               
               JOptionPane.showMessageDialog(null, "No estan");
               
               }
            
            
           
       }catch(Exception e){
           
           JOptionPane.showMessageDialog(null, "Error");
           
       }
       
       
           
        
        
          
        
    }//GEN-LAST:event_btnBuscarActionPerformed

public void cboBuscarConsulta(){
        try{
          
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/siu", "root", "compromiso");
        PreparedStatement pst = cn.prepareStatement("select carnet_alumno from alumnos");
            ResultSet rs = pst.executeQuery();

            cboBuscar.addItem("Seleccione una opción");
            while (rs.next()) {
                cboBuscar.addItem(rs.getString("carnet_alumno"));
                
            }  
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e,"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cboBuscar;
    private javax.swing.JTable combo;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
